dist: jammy # Ubuntu 22.04
language: python
python:
  - "3.10"
  - "3.11"
  - "3.12"
# Travis CI doesn't support 3.13 yet
install:
  - python -m pip install pytest requests watchdog
script:
  - make test-travis
